### PR TITLE
Fix: Types for CurrentResponse

### PR DESCRIPTION
**Pull request by looskie**
CurrentResponse is a bit outdated, I've updated the types.

Also I've removed the URL to get the types, (sample.openweathermap.*) because sample. is outdated.

### CODE REVIEW

**Comment by boon-cpu** [comment]
Nah :+1:

**Comment by looskie** [comment]
> Nah 👍

**Review by boon-cpu — APPROVED** [review]
?

**Comment by alii** [comment]
Looks PR to me. 👍😂✅

**Review by alii — APPROVED** [review]
46C947CA-7EBA-4D9C-8105-F346D7782903

**Comment by looskie** [comment]
gift from phin

**Comment by boon-cpu** [comment]
image

**Review by Phineas — APPROVED** [review]

**Comment by ghost** [comment]
Thanks y'all

**Comment by alii** [comment]
image

# Thanks for merge

**Comment by bfu4** [comment]
## Thanks for merge

**Comment by looskie** [comment]
<h3>Thanks for merge </h3>

**Comment by hexiro** [comment]
image
### Thanks for merge

**Comment by pxseu** [comment]
image
### Thanks for merge

**Pull request merged**
